name = "chickenroad-review-com-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=chickenroad-review.com.de"
HMAC_KEY = "3b98d1352a362f7c9fbe45bb438aa3b5d6c643c2e530baa472a253c8fcac4afc"
COOKIE_NAME = "01k"
PLAY_PATH = "play-now"
BUTTON_ID = "p909b6591161e789bb25106e550d41b09"
GATE_SALT = "6fdfbf4f2ccab86d"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "aums"
CTA_SELECTOR = ".play-button"
